const RULE_TEXT = "Ударение — это секретная сила слова. Мы просто учимся её находить!";
const RULE_ID = 3;

export const accentTasks = [
  // === 1. СУЩЕСТВИТЕЛЬНЫЕ ===

  // Техника и материалы
  { type: "accent", word: "газопровод", question: null, correct: "газопровОд", options: ["газопрОвод", "газопровОд", "гАзопровод"], audio: "Газ идёт по провОду! Ударение на О в конце!", hint: "Запомни: водопровОд, газопровОд — ударение всегда на последнем О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "нефтепровод", question: null, correct: "нефтепровОд", options: ["нефтепрОвод", "нефтепровОд", "нЕфтепровод"], audio: "Нефть течёт по провОду! Как газопровОд!", hint: "ПровОд — от слова «проводить». Ударение на последнем О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "инструмент", question: null, correct: "инструмЕнт", options: ["инстрУмент", "инструмЕнт", "Инструмент"], audio: "ИнструмЕнт — нужный предмет! Ударение на Е!", hint: "ИнструмЕнт рифмуется с «момЕнт» — ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "кремень", question: null, correct: "кремЕнь", options: ["крЕмень", "кремЕнь"], audio: "Твёрдый как кремЕнь! Ударение на Е!", hint: "КремЕнь — камень. Ударение на втором слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "лоскут", question: null, correct: "лоскУт", options: ["лОскут", "лоскУт"], audio: "Маленький лоскУт ткани! Ударение на У!", hint: "ЛоскУт — кусочек ткани. Ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "ломоть", question: null, correct: "ломОть", options: ["лОмоть", "ломОть"], audio: "Отрежь ломОть хлеба! Ударение на О!", hint: "ЛомОть — кусок. Ударение на втором слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "ремень", question: null, correct: "ремЕнь", options: ["рЕмень", "ремЕнь"], audio: "Застегни ремЕнь! Ударение на Е!", hint: "РемЕнь — как кремЕнь, ударение на втором слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "цемент", question: null, correct: "цемЕнт", options: ["цЕмент", "цемЕнт"], audio: "Крепкий цемЕнт! Ударение на Е!", hint: "ЦемЕнт рифмуется с «момЕнт»!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // Профессии и люди
  { type: "accent", word: "бухгалтер", question: null, correct: "бухгАлтер", options: ["бухгАлтер", "бухгалтЕр", "бУхгалтер"], audio: "БухгАлтер считает деньги! Ударение на А!", hint: "БухгАлтер — ударение на А! И во множественном числе: бухгАлтеры!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "столяр", question: null, correct: "столЯр", options: ["стОляр", "столЯр"], audio: "СтолЯр делает столы и стулья! Ударение на Я!", hint: "СтолЯр — мастер по дереву. Ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "хозяева", question: null, correct: "хозЯева", options: ["хозяевА", "хозЯева", "хОзяева"], audio: "ХозЯева дома встречают гостей! Ударение на Я!", hint: "ХозЯин — хозЯева. Ударение остаётся на Я!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "сирота", question: null, correct: "сиротА", options: ["сирОта", "сиротА", "сИрота"], audio: "СиротА — ударение на последнем А!", hint: "СиротА — ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // Документы и измерения
  { type: "accent", word: "документ", question: null, correct: "докумЕнт", options: ["докУмент", "докумЕнт", "дОкумент"], audio: "Важный докумЕнт! Ударение на Е!", hint: "ДокумЕнт — как инструмЕнт, ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "договор", question: null, correct: "договОр", options: ["дОговор", "договОр", "догОвор"], audio: "Подписываем договОр! Ударение на последнем О!", hint: "ДоговОр — ударение на последнем слоге! Запомни: договОр, а не дОговор!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "квартал", question: null, correct: "квартАл", options: ["квАртал", "квартАл"], audio: "КвартАл — и часть города, и часть года! Ударение на А!", hint: "КвартАл — всегда на последнем слоге, в любом значении!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "процент", question: null, correct: "процЕнт", options: ["прОцент", "процЕнт"], audio: "Сто процЕнтов правильно! Ударение на Е!", hint: "ПроцЕнт — ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "километр", question: null, correct: "киломЕтр", options: ["килОметр", "киломЕтр", "кИлометр"], audio: "Один киломЕтр — тысяча метров! Ударение на Е!", hint: "КиломЕтр, сантимЕтр — ударение всегда на Е в слове «мЕтр»!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "сантиметр", question: null, correct: "сантимЕтр", options: ["сантИметр", "сантимЕтр", "сАнтиметр"], audio: "Маленький сантимЕтр! Ударение на Е, как в слове «мЕтр»!", hint: "СантимЕтр — ударение на Е! Как в киломЕтр!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // Предметы и быт
  { type: "accent", word: "алфавит", question: null, correct: "алфавИт", options: ["алфАвит", "алфавИт", "Алфавит"], audio: "Учим алфавИт! Ударение на И!", hint: "АлфавИт — ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "арбуз", question: null, correct: "арбУз", options: ["Арбуз", "арбУз"], audio: "Сладкий арбУз! Ударение на У!", hint: "АрбУз — ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "банты", question: null, correct: "бАнты", options: ["бАнты", "бантЫ"], audio: "Красивые бАнты в волосах! Ударение на А!", hint: "БАнт — бАнты! Ударение не убегает, остаётся на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "ворота", question: null, correct: "ворОта", options: ["вОрота", "ворОта", "воротА"], audio: "Открывай ворОта! Ударение на О!", hint: "ВорОта — ударение на втором О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "жалюзи", question: null, correct: "жалюзИ", options: ["жАлюзи", "жалЮзи", "жалюзИ"], audio: "Модные жалюзИ на окнах! Ударение на И!", hint: "ЖалюзИ — французское слово, ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "краны", question: null, correct: "крАны", options: ["крАны", "кранЫ"], audio: "Строительные крАны! Ударение на А!", hint: "КрАн — крАны! Ударение не убегает!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "магазин", question: null, correct: "магазИн", options: ["магАзин", "магазИн", "мАгазин"], audio: "Идём в магазИн! Ударение на И!", hint: "МагазИн — ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "портфель", question: null, correct: "портфЕль", options: ["пОртфель", "портфЕль"], audio: "Собираем портфЕль в школу! Ударение на Е!", hint: "ПортфЕль — ударение на Е! Как ремЕнь!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "статуя", question: null, correct: "стАтуя", options: ["стАтуя", "статУя", "статуЯ"], audio: "Красивая стАтуя в парке! Ударение на А!", hint: "СтАтуя — ударение на первом А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "хвоя", question: null, correct: "хвОя", options: ["хвОя", "хвоЯ"], audio: "Зелёная хвОя на ёлке! Ударение на О!", hint: "ХвОя — ударение на О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // Природа и наука
  { type: "accent", word: "дремота", question: null, correct: "дремОта", options: ["дрЕмота", "дремОта", "дремотА"], audio: "Сладкая дремОта после обеда! Ударение на О!", hint: "ДремОта — от слова «дремАть». Ударение на О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "добыча", question: null, correct: "добЫча", options: ["дОбыча", "добЫча", "добычА"], audio: "Ценная добЫча! Ударение на Ы!", hint: "ДобЫча — ударение на Ы!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "жаворонок", question: null, correct: "жАворонок", options: ["жАворонок", "жавОронок", "жаворОнок"], audio: "Птичка жАворонок поёт в небе! Ударение на А!", hint: "ЖАворонок — ударение на первом А! И во множественном: жАворонки!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "искра", question: null, correct: "Искра", options: ["Искра", "искрА"], audio: "Яркая Искра от костра! Ударение на И!", hint: "Искра — ударение на первом слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "орфография", question: null, correct: "орфогрАфия", options: ["орфОграфия", "орфогрАфия", "орфографИя"], audio: "Учим орфогрАфию — правильное написание! Ударение на А!", hint: "ОрфогрАфия — ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "кулинария", question: null, correct: "кулинарИя", options: ["кулинАрия", "кулинарИя", "кУлинария"], audio: "Вкусная кулинарИя! Ударение на И!", hint: "КулинарИя — ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "санитария", question: null, correct: "санитарИя", options: ["санитАрия", "санитарИя", "сАнитария"], audio: "Чистота и санитарИя! Ударение на И!", hint: "СанитарИя — как кулинарИя, ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "силос", question: null, correct: "сИлос", options: ["сИлос", "силОс"], audio: "Корм для коров — сИлос! Ударение на И!", hint: "СИлос — ударение на первом слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },

  // === 2. ГЛАГОЛЫ ===

  // На -ИТЬ / -ИТ
  { type: "accent", word: "включит", question: null, correct: "включИт", options: ["вклЮчит", "включИт"], audio: "Он включИт свет! Ударение на И!", hint: "ВключИть — включИт. Глаголы на -ИТЬ сохраняют ударение!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "звонит", question: null, correct: "звонИт", options: ["звОнит", "звонИт"], audio: "Телефон звонИт! Ударение на И!", hint: "ЗвонИть — звонИт — звонИм — звонЯт! Ударение всегда на И или Я!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "положил", question: null, correct: "положИл", options: ["полОжил", "положИл", "пОложил"], audio: "Он положИл книгу на стол! Ударение на И!", hint: "ПоложИть — положИл. Ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "повторит", question: null, correct: "повторИт", options: ["повтОрит", "повторИт", "пОвторит"], audio: "Он повторИт правило! Ударение на И!", hint: "ПовторИть — повторИт — повторИм. Ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "перезвонит", question: null, correct: "перезвонИт", options: ["перезвОнит", "перезвонИт", "пЕрезвонит"], audio: "Она перезвонИт позже! Ударение на И!", hint: "Как звонИт, так и перезвонИт — ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // Действия
  { type: "accent", word: "баловать", question: null, correct: "баловАть", options: ["бАловать", "баловАть", "балОвать"], audio: "Не надо баловАть! Ударение на А в конце!", hint: "БаловАть — ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "закупорить", question: null, correct: "закУпорить", options: ["закУпорить", "закупОрить", "закупорИть"], audio: "ЗакУпорить бутылку! Ударение на У!", hint: "ЗакУпорить — откУпорить. Ударение на У!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "начать", question: null, correct: "начАть", options: ["нАчать", "начАть"], audio: "Пора начАть урок! Ударение на А!", hint: "НачАть — ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "ходатайствовать", question: null, correct: "ходАтайствовать", options: ["ходатАйствовать", "ходАтайствовать", "ходатайствовАть"], audio: "ХодАтайствовать — просить за кого-то! Ударение на А!", hint: "ХодАтайство — ходАтайствовать. Ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },

  // Женский род (ударение на А в конце)
  { type: "accent", word: "брала", question: null, correct: "бралА", options: ["брАла", "бралА"], audio: "Она бралА книгу! Ударение на последнем А!", hint: "В женском роде прошедшего времени ударение часто уходит на А: бралА!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "взяла", question: null, correct: "взялА", options: ["взЯла", "взялА"], audio: "Она взялА зонт! Ударение на А!", hint: "ВзялА — ударение на последнем А, как у всех глаголов женского рода!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "гнала", question: null, correct: "гналА", options: ["гнАла", "гналА"], audio: "Она гналА мяч! Ударение на А!", hint: "ГналА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "звала", question: null, correct: "звалА", options: ["звАла", "звалА"], audio: "Она звалА друга! Ударение на А!", hint: "ЗвалА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "занята", question: null, correct: "занятА", options: ["зАнята", "занЯта", "занятА"], audio: "Она занятА делом! Ударение на последнем А!", hint: "ЗанятА — в женском роде ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "начала", question: null, correct: "началА", options: ["нАчала", "начАла", "началА"], audio: "Она началА работу! Ударение на последнем А!", hint: "НачалА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "начата", question: null, correct: "начатА", options: ["нАчата", "начАта", "начатА"], audio: "Работа начатА! Ударение на А!", hint: "НачатА — как началА, ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "ожила", question: null, correct: "ожилА", options: ["ожИла", "ожилА"], audio: "Природа ожилА весной! Ударение на А!", hint: "ОжилА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "поняла", question: null, correct: "понялА", options: ["пОняла", "понЯла", "понялА"], audio: "Она всё понялА! Ударение на последнем А!", hint: "ПонялА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "порвала", question: null, correct: "порвалА", options: ["порвАла", "порвалА", "пОрвала"], audio: "Она порвалА бумагу! Ударение на А!", hint: "ПорвалА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "подняла", question: null, correct: "поднялА", options: ["пОдняла", "поднЯла", "поднялА"], audio: "Она поднялА руку! Ударение на А!", hint: "ПоднялА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "плыла", question: null, correct: "плылА", options: ["плЫла", "плылА"], audio: "Она плылА по реке! Ударение на А!", hint: "ПлылА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "проспала", question: null, correct: "проспалА", options: ["проспАла", "проспалА", "прОспала"], audio: "Она проспалА урок! Ударение на А!", hint: "ПроспалА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "лилась", question: null, correct: "лилАсь", options: ["лИлась", "лилАсь"], audio: "Вода лилАсь ручьём! Ударение на А!", hint: "ЛилАсь — ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "нажилась", question: null, correct: "нажилАсь", options: ["нажИлась", "нажилАсь", "нАжилась"], audio: "НажилАсь — ударение на последнем А!", hint: "НажилАсь — ударение на А в конце!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "кралась", question: null, correct: "кралАсь", options: ["крАлась", "кралАсь"], audio: "Кошка кралАсь тихо! Ударение на А!", hint: "КралАсь — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },

  // Мужской и средний род, множественное число
  { type: "accent", word: "взяли", question: null, correct: "взЯли", options: ["взЯли", "взялИ"], audio: "Они взЯли книги! Ударение на Я!", hint: "ВзЯли — во множественном числе ударение на Я!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "занят", question: null, correct: "зАнят", options: ["зАнят", "занЯт"], audio: "Он зАнят работой! Ударение на А!", hint: "ЗАнят — в мужском роде ударение на А! Но она — занятА!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "задал", question: null, correct: "зАдал", options: ["зАдал", "задАл"], audio: "Учитель зАдал задание! Ударение на А!", hint: "ЗАдал — ударение на первом слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "начато", question: null, correct: "нАчато", options: ["нАчато", "начАто", "начатО"], audio: "Дело нАчато! Ударение на А!", hint: "НАчато — в среднем роде ударение на первом А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "нажил", question: null, correct: "нАжил", options: ["нАжил", "нажИл"], audio: "Он нАжил богатство! Ударение на А!", hint: "НАжил — ударение на первом слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "наняли", question: null, correct: "нАняли", options: ["нАняли", "нанЯли", "нанялИ"], audio: "Они нАняли работника! Ударение на А!", hint: "НАняли — ударение на первом А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "ожил", question: null, correct: "Ожил", options: ["Ожил", "ожИл"], audio: "Цветок Ожил после дождя! Ударение на О!", hint: "Ожил — ударение на О! Но она — ожилА!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "понял", question: null, correct: "пОнял", options: ["пОнял", "понЯл"], audio: "Он пОнял задачу! Ударение на О!", hint: "ПОнял — ударение на О! Но она — понялА!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "принял", question: null, correct: "прИнял", options: ["прИнял", "принЯл"], audio: "Он прИнял решение! Ударение на И!", hint: "ПрИнял — ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "поднял", question: null, correct: "пОднял", options: ["пОднял", "поднЯл"], audio: "Он пОднял руку! Ударение на О!", hint: "ПОднял — ударение на О! Но она — поднялА!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "сняли", question: null, correct: "снЯли", options: ["снЯли", "снялИ"], audio: "Они снЯли шапки! Ударение на Я!", hint: "СнЯли — ударение на Я!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // === 3. ПРИЛАГАТЕЛЬНЫЕ И НАРЕЧИЯ ===

  // Прилагательные
  { type: "accent", word: "августовский", question: null, correct: "Августовский", options: ["Августовский", "августОвский", "августовскИй"], audio: "Августовский вечер! Ударение на А!", hint: "Августовский — от слова «Август», ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "безудержный", question: null, correct: "безУдержный", options: ["безУдержный", "безудЕржный", "безудержнОй"], audio: "БезУдержный смех! Ударение на У!", hint: "БезУдержный — ударение на У!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "кухонный", question: null, correct: "кУхонный", options: ["кУхонный", "кухОнный"], audio: "КУхонный стол! Ударение на У!", hint: "КУхонный — от слова «кУхня», ударение на У!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "красивее", question: null, correct: "красИвее", options: ["крАсивее", "красИвее", "красивЕе"], audio: "Ещё красИвее! Ударение на И!", hint: "КрасИво — красИвее — ударение всегда на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "оптовый", question: null, correct: "оптОвый", options: ["Оптовый", "оптОвый", "оптовОй"], audio: "ОптОвый магазин! Ударение на О!", hint: "ОптОвый — ударение на втором О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "сливовый", question: null, correct: "слИвовый", options: ["слИвовый", "сливОвый"], audio: "СлИвовый сок! Ударение на И!", hint: "СлИвовый — от слова «слИва», ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // Краткие формы
  { type: "accent", word: "вредна", question: null, correct: "вреднА", options: ["врЕдна", "вреднА"], audio: "Эта привычка вреднА! Ударение на А!", hint: "ВреднА — в женском роде ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "груба", question: null, correct: "грубА", options: ["грУба", "грубА"], audio: "Ткань грубА на ощупь! Ударение на А!", hint: "ГрубА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "молода", question: null, correct: "молодА", options: ["мОлода", "молОда", "молодА"], audio: "Она ещё молодА! Ударение на А!", hint: "МолодА — ударение на последнем А! Но мОлодо — на О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "правы", question: null, correct: "прАвы", options: ["прАвы", "правЫ"], audio: "Вы прАвы! Ударение на А!", hint: "ПрАвы — ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "пуста", question: null, correct: "пустА", options: ["пУста", "пустА"], audio: "Коробка пустА! Ударение на А!", hint: "ПустА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "созвана", question: null, correct: "сОзвана", options: ["сОзвана", "созвАна", "созванА"], audio: "Комиссия сОзвана! Ударение на О!", hint: "СОзвана — ударение на О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "продано", question: null, correct: "прОдано", options: ["прОдано", "продАно", "проданО"], audio: "Всё прОдано! Ударение на О!", hint: "ПрОдано — ударение на О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "прожиты", question: null, correct: "прОжиты", options: ["прОжиты", "прожИты", "прожитЫ"], audio: "Годы прОжиты не зря! Ударение на О!", hint: "ПрОжиты — ударение на О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },

  // Наречия
  { type: "accent", word: "доверху", question: null, correct: "дОверху", options: ["дОверху", "довЕрху", "доверхУ"], audio: "Налил дОверху! Ударение на О!", hint: "ДОверху — ударение на первом О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "донельзя", question: null, correct: "донЕльзя", options: ["дОнельзя", "донЕльзя", "донельзЯ"], audio: "Устал донЕльзя! Ударение на Е!", hint: "ДонЕльзя — ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "завидно", question: null, correct: "завИдно", options: ["зАвидно", "завИдно", "завиднО"], audio: "Как завИдно! Ударение на И!", hint: "ЗавИдно — ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "издавна", question: null, correct: "Издавна", options: ["Издавна", "издАвна", "издавнА"], audio: "Издавна так повелось! Ударение на И!", hint: "Издавна — ударение на первом слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "изредка", question: null, correct: "Изредка", options: ["Изредка", "изрЕдка", "изредкА"], audio: "Изредка бывает дождь! Ударение на И!", hint: "Изредка — ударение на первом слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "набело", question: null, correct: "нАбело", options: ["нАбело", "набЕло", "набелО"], audio: "Переписать нАбело! Ударение на А!", hint: "НАбело — ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "наголо", question: null, correct: "нАголо", options: ["нАголо", "нагОло", "наголО"], audio: "Подстричь нАголо! Ударение на А!", hint: "НАголо — ударение на первом А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },

  // Дополнительные слова из оригинального набора
  { type: "accent", word: "торты", question: null, correct: "тОрты", options: ["тОрты", "тортЫ"], audio: "Вкусные тОрты! Ударение на О!", hint: "ТОрт — тОрты! Ударение не убегает!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "щавель", question: null, correct: "щавЕль", options: ["щАвель", "щавЕль"], audio: "Зелёный щавЕль! Ударение на Е!", hint: "ЩавЕль рифмуется с портфЕль!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // === ДОПОЛНИТЕЛЬНЫЕ СЛОВА ===

  // Формы существительных
  { type: "accent", word: "бухгалтеры", question: null, correct: "бухгАлтеры", options: ["бухгАлтеры", "бухгалтерЫ", "бухгалтЕры"], audio: "Много бухгАлтеров! Ударение на А, как в единственном числе!", hint: "БухгАлтер — бухгАлтеры! Ударение не убегает!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "жаворонки", question: null, correct: "жАворонки", options: ["жАворонки", "жавОронки", "жаворОнки"], audio: "Птички жАворонки! Ударение на А!", hint: "ЖАворонок — жАворонки! Ударение остаётся на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "средства", question: null, correct: "срЕдства", options: ["срЕдства", "средствА", "средстВА"], audio: "Денежные срЕдства! Ударение на Е!", hint: "СрЕдство — срЕдства! Ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "центнер", question: null, correct: "цЕнтнер", options: ["цЕнтнер", "центнЕр"], audio: "Один цЕнтнер — это 100 кг! Ударение на Е!", hint: "ЦЕнтнер — ударение на первом Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "шарфы", question: null, correct: "шАрфы", options: ["шАрфы", "шарфЫ"], audio: "Тёплые шАрфы! Ударение на А!", hint: "ШАрф — шАрфы! Ударение не убегает!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "шофёр", question: null, correct: "шофЁр", options: ["шОфер", "шофЁр"], audio: "ШофЁр за рулём! Ударение на Ё!", hint: "ШофЁр — ударение на Ё! Всегда!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "досуг", question: null, correct: "досУг", options: ["дОсуг", "досУг"], audio: "На досУге читаем книги! Ударение на У!", hint: "ДосУг — ударение на У!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "каталог", question: null, correct: "каталОг", options: ["катАлог", "каталОг", "кАталог"], audio: "Открой каталОг! Ударение на О!", hint: "КаталОг — ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "крапива", question: null, correct: "крапИва", options: ["крАпива", "крапИва", "крапивА"], audio: "Жгучая крапИва! Ударение на И!", hint: "КрапИва — ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "кладовая", question: null, correct: "кладовАя", options: ["клАдовая", "кладОвая", "кладовАя"], audio: "Полная кладовАя! Ударение на А!", hint: "КладовАя — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "ненависть", question: null, correct: "нЕнависть", options: ["нЕнависть", "ненАвисть", "ненавИсть"], audio: "НЕнависть — ударение на первом Е!", hint: "НЕнависть — ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "намерение", question: null, correct: "намЕрение", options: ["нАмерение", "намЕрение", "намерЕние"], audio: "Доброе намЕрение! Ударение на Е!", hint: "НамЕрение — ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "медведями", question: null, correct: "медвЕдями", options: ["медвЕдями", "медведЯми", "мЕдведями"], audio: "Любуемся медвЕдями! Ударение на Е!", hint: "МедвЕдь — медвЕдями! Ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // Дополнительные формы глаголов
  { type: "accent", word: "взялись", question: null, correct: "взЯлись", options: ["взЯлись", "взялИсь"], audio: "Они взЯлись за дело! Ударение на Я!", hint: "ВзЯлись — ударение на Я!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "взялся", question: null, correct: "взЯлся", options: ["взЯлся", "взялсЯ"], audio: "Он взЯлся за работу! Ударение на Я!", hint: "ВзЯлся — ударение на Я!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "взяты", question: null, correct: "взЯты", options: ["взЯты", "взятЫ"], audio: "Книги взЯты! Ударение на Я!", hint: "ВзЯты — ударение на Я!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "гналась", question: null, correct: "гнАлась", options: ["гнАлась", "гналАсь"], audio: "Кошка гнАлась за мышкой! Ударение на А!", hint: "ГнАлась — ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "дрались", question: null, correct: "дрАлись", options: ["дрАлись", "дралИсь"], audio: "Они дрАлись! Ударение на А!", hint: "ДрАлись — ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "звонить", question: null, correct: "звонИть", options: ["звОнить", "звонИть"], audio: "ЗвонИть по телефону! Ударение на И!", hint: "ЗвонИть — ударение всегда на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "звоним", question: null, correct: "звонИм", options: ["звОним", "звонИм"], audio: "Мы звонИм другу! Ударение на И!", hint: "ЗвонИть — звонИм! Ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "звонишь", question: null, correct: "звонИшь", options: ["звОнишь", "звонИшь"], audio: "Ты звонИшь маме! Ударение на И!", hint: "ЗвонИть — звонИшь! Ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "звонят", question: null, correct: "звонЯт", options: ["звОнят", "звонЯт"], audio: "Они звонЯт в дверь! Ударение на Я!", hint: "ЗвонИть — звонЯт! Ударение на Я!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "дозвонишься", question: null, correct: "дозвонИшься", options: ["дозвОнишься", "дозвонИшься"], audio: "Не дозвонИшься никак! Ударение на И!", hint: "Как звонИшь, так и дозвонИшься!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "позвонят", question: null, correct: "позвонЯт", options: ["позвОнят", "позвонЯт"], audio: "Они позвонЯт вечером! Ударение на Я!", hint: "Как звонЯт, так и позвонЯт!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "занял", question: null, correct: "зАнял", options: ["зАнял", "занЯл"], audio: "Он зАнял первое место! Ударение на А!", hint: "ЗАнял — ударение на А! Но она — занялА!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "заняла", question: null, correct: "занялА", options: ["зАняла", "занЯла", "занялА"], audio: "Она занялА очередь! Ударение на А в конце!", hint: "ЗанялА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "заняли", question: null, correct: "зАняли", options: ["зАняли", "занЯли", "занялИ"], audio: "Они зАняли свои места! Ударение на А!", hint: "ЗАняли — ударение на первом А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "задаст", question: null, correct: "задАст", options: ["зАдаст", "задАст"], audio: "Учитель задАст вопрос! Ударение на А!", hint: "ЗадАст — ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "задала", question: null, correct: "задалА", options: ["зАдала", "задАла", "задалА"], audio: "Она задалА вопрос! Ударение на последнем А!", hint: "ЗадалА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "задали", question: null, correct: "зАдали", options: ["зАдали", "задАли", "задалИ"], audio: "Нам зАдали уроки! Ударение на А!", hint: "ЗАдали — ударение на первом А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "избаловать", question: null, correct: "избаловАть", options: ["избАловать", "избаловАть", "избалОвать"], audio: "Не надо избаловАть! Ударение на А!", hint: "БаловАть — избаловАть! Ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "премировать", question: null, correct: "премировАть", options: ["премИровать", "премирОвать", "премировАть"], audio: "ПремировАть за успехи! Ударение на А!", hint: "ПремировАть — как баловАть, ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "облегчить", question: null, correct: "облегчИть", options: ["облЕгчить", "облегчИть"], audio: "ОблегчИть задачу! Ударение на И!", hint: "ОблегчИть — ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "откупорить", question: null, correct: "откУпорить", options: ["откУпорить", "откупОрить", "откупорИть"], audio: "ОткУпорить бутылку! Ударение на У!", hint: "ОткУпорить — как закУпорить, ударение на У!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "начался", question: null, correct: "началсЯ", options: ["нАчался", "начАлся", "началсЯ"], audio: "Урок началсЯ! Ударение на Я!", hint: "НачалсЯ — ударение на последнем слоге!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "нанялся", question: null, correct: "нАнялся", options: ["нАнялся", "нанЯлся", "нанялсЯ"], audio: "Он нАнялся на работу! Ударение на А!", hint: "НАнялся — ударение на первом А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "крался", question: null, correct: "крАлся", options: ["крАлся", "кралсЯ"], audio: "Кот крАлся тихо! Ударение на А!", hint: "КрАлся — ударение на А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "лился", question: null, correct: "лИлся", options: ["лИлся", "лилсЯ"], audio: "Дождь лИлся весь день! Ударение на И!", hint: "ЛИлся — ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "попила", question: null, correct: "попилА", options: ["попИла", "попилА", "пОпила"], audio: "Она попилА воды! Ударение на А!", hint: "ПопилА — ударение на последнем А!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "поняли", question: null, correct: "пОняли", options: ["пОняли", "понЯли", "понялИ"], audio: "Все пОняли задание! Ударение на О!", hint: "ПОняли — ударение на О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "положит", question: null, correct: "полОжит", options: ["полОжит", "положИт", "пОложит"], audio: "Он полОжит книгу! Ударение на О!", hint: "ПолОжит — ударение на второе О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "повторим", question: null, correct: "повторИм", options: ["повтОрим", "повторИм"], audio: "Мы повторИм правило! Ударение на И!", hint: "ПовторИть — повторИм! Ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "приняли", question: null, correct: "прИняли", options: ["прИняли", "принЯли", "принялИ"], audio: "Они прИняли решение! Ударение на И!", hint: "ПрИняли — ударение на И!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "подняли", question: null, correct: "пОдняли", options: ["пОдняли", "поднЯли", "поднялИ"], audio: "Все пОдняли руки! Ударение на О!", hint: "ПОдняли — ударение на О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },

  // Дополнительные прилагательные и наречия
  { type: "accent", word: "вредны", question: null, correct: "врЕдны", options: ["врЕдны", "вреднЫ"], audio: "Эти привычки врЕдны! Ударение на Е!", hint: "ВрЕдны — во множественном числе ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "молодо", question: null, correct: "мОлодо", options: ["мОлодо", "молОдо", "молодО"], audio: "МОлодо-зелено! Ударение на О!", hint: "МОлодо — ударение на первом О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "созваны", question: null, correct: "сОзваны", options: ["сОзваны", "созвАны", "созванЫ"], audio: "Все сОзваны на собрание! Ударение на О!", hint: "СОзваны — ударение на О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
  { type: "accent", word: "глубоко", question: null, correct: "глубокО", options: ["глУбоко", "глубОко", "глубокО"], audio: "Очень глубокО! Ударение на последнем О!", hint: "ГлубокО — ударение на последнем О!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 1, category: "accent" },
  { type: "accent", word: "черпать", question: null, correct: "чЕрпать", options: ["чЕрпать", "черпАть"], audio: "ЧЕрпать воду ковшом! Ударение на Е!", hint: "ЧЕрпать — ударение на Е!", rule: RULE_TEXT, ruleId: RULE_ID, difficulty: 2, category: "accent" },
];
