const RULE_SOUNDS = "Звуки мы слышим, а буквы — пишем. Иногда они не совпадают, и это нормально!";
const RULE_ID_PHONETICS = 56;

const RULE_TRANSFER = "Слово переносится по слогам. В каждом слоге — обязательно гласная!";
const RULE_ID_TRANSFER = 80;

export const phoneticsTasks = [
  // ============================================================
  // БЛОК 1: ГЛАСНЫЕ И СОГЛАСНЫЕ ЗВУКИ (базовый)
  // ============================================================

  { type: "phonetics", word: "дом", question: "Сколько гласных звуков в слове «дом»?", correct: "1", options: ["1", "2", "3"], audio: "Д-О-М. Гласный только один — О!", hint: "Гласные — это звуки, которые можно тянуть и петь: А, О, У, Э, И, Ы.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "молоко", question: "Сколько гласных звуков в слове «молоко»?", correct: "3", options: ["2", "3", "4"], audio: "М-О-Л-О-К-О. Три гласных: О, О, О!", hint: "Сколько гласных — столько и слогов! Мо-ло-ко.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "стол", question: "Сколько согласных звуков в слове «стол»?", correct: "3", options: ["2", "3", "4"], audio: "С-Т-О-Л. Согласные: С, Т, Л. Их три!", hint: "Согласные нельзя пропеть — они шумят, свистят, рычат!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "карандаш", question: "Сколько слогов в слове «карандаш»?", correct: "3", options: ["2", "3", "4"], audio: "Ка-ран-даш. Три слога, три гласных!", hint: "Сколько гласных — столько и слогов!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "ученик", question: "Сколько слогов в слове «ученик»?", correct: "3", options: ["2", "3", "4"], audio: "У-че-ник. Три гласных — три слога!", hint: "Посчитай гласные: У, Е, И. Сколько гласных — столько слогов!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // ============================================================
  // БЛОК 2: БУКВЫ Е, Ё, Ю, Я — ДВА ЗВУКА
  // ============================================================

  // В начале слова
  { type: "phonetics", word: "ёж", question: "Сколько звуков в слове «ёж»?", correct: "3", options: ["2", "3", "4"], audio: "Буква Ё в начале слова даёт два звука: Й + О. Й-О-Ж = 3 звука!", hint: "Ё в начале слова = два звука: [Й'] + [О].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "яблоко", question: "Сколько звуков в слове «яблоко»?", correct: "7", options: ["6", "7", "8"], audio: "Буква Я в начале слова даёт два звука: Й + А. Й-А-Б-Л-О-К-О = 7!", hint: "Я в начале слова = [Й'] + [А]. Посчитай все звуки!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "ель", question: "Сколько звуков в слове «ель»?", correct: "3", options: ["2", "3", "4"], audio: "Е в начале даёт два звука: Й-Э. А мягкий знак звука не имеет. Й-Э-Л' = 3!", hint: "Е в начале = [Й'] + [Э]. Мягкий знак не даёт звука!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "юла", question: "Сколько звуков в слове «юла»?", correct: "4", options: ["3", "4", "5"], audio: "Ю в начале = два звука: Й + У. Й-У-Л-А = 4 звука!", hint: "Ю в начале слова = [Й'] + [У].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "ёлка", question: "Сколько звуков в слове «ёлка»?", correct: "5", options: ["4", "5", "6"], audio: "Ё в начале = Й + О. Й-О-Л-К-А = 5 звуков!", hint: "Ё в начале слова всегда даёт два звука!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "яма", question: "Сколько звуков в слове «яма»?", correct: "4", options: ["3", "4", "5"], audio: "Я в начале = Й + А. Й-А-М-А = 4 звука!", hint: "Я в начале слова = [Й'] + [А].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "юг", question: "Сколько звуков в слове «юг»?", correct: "3", options: ["2", "3", "4"], audio: "Ю в начале = Й + У. Й-У-Г = 3 звука!", hint: "Ю в начале = два звука: [Й'] + [У].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "ёрш", question: "Сколько звуков в слове «ёрш»?", correct: "4", options: ["3", "4", "5"], audio: "Ё в начале = Й + О. Й-О-Р-Ш = 4 звука!", hint: "Ё в начале слова = два звука!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // После гласной
  { type: "phonetics", word: "маяк", question: "Сколько звуков в слове «маяк»?", correct: "5", options: ["4", "5", "6"], audio: "Я после гласной А тоже даёт два звука! М-А-Й-А-К = 5!", hint: "Я после гласной = [Й'] + [А].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "поёт", question: "Сколько звуков в слове «поёт»?", correct: "5", options: ["4", "5", "6"], audio: "Ё после гласной О даёт два звука! П-О-Й-О-Т = 5!", hint: "Ё после гласной = [Й'] + [О].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "каюта", question: "Сколько звуков в слове «каюта»?", correct: "6", options: ["5", "6", "7"], audio: "Ю после гласной А даёт два звука! К-А-Й-У-Т-А = 6!", hint: "Ю после гласной = [Й'] + [У].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "моет", question: "Сколько звуков в слове «моет»?", correct: "5", options: ["4", "5", "6"], audio: "Е после гласной О даёт два звука! М-О-Й-Э-Т = 5!", hint: "Е после гласной = [Й'] + [Э].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "стоят", question: "Сколько звуков в слове «стоят»?", correct: "6", options: ["5", "6", "7"], audio: "Я после гласной О даёт два звука! С-Т-О-Й-А-Т = 6!", hint: "Я после гласной = [Й'] + [А].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "заяц", question: "Сколько звуков в слове «заяц»?", correct: "5", options: ["4", "5", "6"], audio: "Я после гласной А даёт два звука! З-А-Й-А-Ц = 5!", hint: "Я после гласной = [Й'] + [А].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // После Ъ и Ь
  { type: "phonetics", word: "вьюга", question: "Сколько звуков в слове «вьюга»?", correct: "5", options: ["4", "5", "6"], audio: "Мягкий знак звука не даёт, а Ю после Ь = два звука! В'-Й-У-Г-А = 5!", hint: "Ь не даёт звука, но Ю после Ь = [Й'] + [У].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "объём", question: "Сколько звуков в слове «объём»?", correct: "5", options: ["4", "5", "6"], audio: "Ъ не даёт звука, а Ё после Ъ = два звука! О-Б-Й-О-М = 5!", hint: "Ъ не даёт звука, но Ё после Ъ = [Й'] + [О].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "семья", question: "Сколько звуков в слове «семья»?", correct: "5", options: ["4", "5", "6"], audio: "Ь не даёт звука, а Я после Ь = два звука! С'-Э-М'-Й-А = 5!", hint: "Ь не даёт звука, но Я после Ь = [Й'] + [А].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "подъезд", question: "Сколько звуков в слове «подъезд»?", correct: "7", options: ["6", "7", "8"], audio: "Ъ не даёт звука, а Е после Ъ = два звука! П-О-Д-Й-Э-З-Д = 7!", hint: "Ъ не даёт звука, но Е после Ъ = [Й'] + [Э].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "льёт", question: "Сколько звуков в слове «льёт»?", correct: "4", options: ["3", "4", "5"], audio: "Ь не даёт звука, а Ё после Ь = два звука! Л'-Й-О-Т = 4!", hint: "Ь не даёт звука, Ё после Ь = [Й'] + [О].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "съел", question: "Сколько звуков в слове «съел»?", correct: "4", options: ["3", "4", "5"], audio: "Ъ не даёт звука, а Е после Ъ = два звука! С-Й-Э-Л = 4!", hint: "Ъ не даёт звука, Е после Ъ = [Й'] + [Э].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "воробьи", question: "Сколько звуков в слове «воробьи»?", correct: "7", options: ["6", "7", "8"], audio: "Ь не даёт звука, а И после Ь = два звука: Й + И! В-О-Р-О-Б'-Й-И = 7!", hint: "И после Ь даёт два звука: [Й'] + [И].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // Е, Ё, Ю, Я после согласной (один звук, смягчает)
  { type: "phonetics", word: "мел", question: "Сколько звуков в слове «мел»?", correct: "3", options: ["2", "3", "4"], audio: "М'-Э-Л. Буква Е после согласной даёт один звук [Э] и смягчает М!", hint: "Е после согласной = один звук [Э], но делает согласную мягкой!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "лёд", question: "Сколько звуков в слове «лёд»?", correct: "3", options: ["2", "3", "4"], audio: "Л'-О-Д. Буква Ё после согласной = один звук [О] и смягчает Л!", hint: "Ё после согласной = один звук [О], делает согласную мягкой!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "люк", question: "Сколько звуков в слове «люк»?", correct: "3", options: ["2", "3", "4"], audio: "Л'-У-К. Буква Ю после согласной = один звук [У] и смягчает Л!", hint: "Ю после согласной = один звук [У], делает согласную мягкой!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "мяч", question: "Сколько звуков в слове «мяч»?", correct: "3", options: ["2", "3", "4"], audio: "М'-А-Ч'. М мягкая из-за Я. Три звука!", hint: "Я после согласной = один звук [А], согласная становится мягкой!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // ============================================================
  // БЛОК 3: МЯГКИЙ И ТВЁРДЫЙ ЗНАКИ — НЕ ДАЮТ ЗВУКА
  // ============================================================

  { type: "phonetics", word: "конь", question: "Сколько звуков в слове «конь»?", correct: "3", options: ["3", "4", "5"], audio: "К-О-Н'. Мягкий знак звука не даёт! 4 буквы, но 3 звука!", hint: "Мягкий знак (Ь) не даёт звука, он только смягчает согласную перед собой.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "день", question: "Сколько звуков в слове «день»?", correct: "3", options: ["3", "4", "5"], audio: "Д'-Э-Н'. Мягкий знак не звук! 4 буквы, 3 звука!", hint: "Ь не даёт звука!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "мальчик", question: "Сколько звуков в слове «мальчик»?", correct: "6", options: ["5", "6", "7"], audio: "М-А-Л'-Ч'-И-К. Мягкий знак звука не даёт! 7 букв, 6 звуков!", hint: "Ь не даёт звука. Посчитай оставшиеся!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "пальто", question: "Сколько звуков в слове «пальто»?", correct: "5", options: ["5", "6", "7"], audio: "П-А-Л'-Т-О. Ь звука не даёт! 6 букв, 5 звуков!", hint: "Мягкий знак не считается звуком!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "объявление", question: "В слове «объявление»: звуков больше, меньше или столько же, сколько букв?", correct: "Звуков больше (10 б., 11 зв.)", options: ["Букв больше", "Звуков больше (10 б., 11 зв.)", "Поровну"], audio: "О-Б-Й-А-В-Л'-Э-Н'-И-Й-Э = 11 звуков! Ъ не звук, но Я после Ъ = [Й'А], и Е на конце после И = [Й'Э]. 10 букв, 11 звуков!", hint: "Ъ не даёт звука, но Я после Ъ = 2 звука, и Е после гласной И тоже = 2 звука!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 4: МЯГКИЕ И ТВЁРДЫЕ СОГЛАСНЫЕ
  // ============================================================

  { type: "phonetics", word: "лёд", question: "Какой первый звук в слове «лёд»?", correct: "[Л'] — мягкий", options: ["[Л] — твёрдый", "[Л'] — мягкий", "[Й']"], audio: "Буква Ё смягчает согласную Л! Получается мягкий [Л']!", hint: "Буквы Е, Ё, И, Ю, Я смягчают согласный перед собой!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "нос", question: "Какой первый звук в слове «нос»?", correct: "[Н] — твёрдый", options: ["[Н] — твёрдый", "[Н'] — мягкий"], audio: "После Н стоит О — она не смягчает! [Н] твёрдый!", hint: "Буквы А, О, У, Э, Ы не смягчают согласный перед собой.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "мир", question: "Какой первый звук в слове «мир»?", correct: "[М'] — мягкий", options: ["[М] — твёрдый", "[М'] — мягкий"], audio: "После М стоит И — она смягчает! [М'] мягкий!", hint: "Буква И смягчает согласный перед собой!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "рука", question: "Какой первый звук в слове «рука»?", correct: "[Р] — твёрдый", options: ["[Р] — твёрдый", "[Р'] — мягкий"], audio: "После Р стоит У — не смягчает. [Р] твёрдый!", hint: "А, О, У, Э, Ы — гласные, которые НЕ смягчают согласный.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "тюлень", question: "Какой первый звук в слове «тюлень»?", correct: "[Т'] — мягкий", options: ["[Т] — твёрдый", "[Т'] — мягкий"], audio: "Ю смягчает Т! Получается мягкий [Т']!", hint: "Буква Ю смягчает согласный перед собой!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "пень", question: "Какой первый звук в слове «пень»?", correct: "[П'] — мягкий", options: ["[П] — твёрдый", "[П'] — мягкий"], audio: "Е смягчает П! [П'] — мягкий!", hint: "Буква Е смягчает согласный перед собой!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "дым", question: "Какой первый звук в слове «дым»?", correct: "[Д] — твёрдый", options: ["[Д] — твёрдый", "[Д'] — мягкий"], audio: "Ы не смягчает! [Д] — твёрдый!", hint: "Буква Ы не смягчает согласный!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // Всегда мягкие: Ч, Щ, Й
  { type: "phonetics", word: "чай", question: "Звук [Ч'] в слове «чай» — мягкий или твёрдый?", correct: "Всегда мягкий", options: ["Твёрдый", "Мягкий", "Всегда мягкий"], audio: "[Ч'] — всегда мягкий! Его нельзя сделать твёрдым!", hint: "Запомни: [Ч'], [Щ'], [Й'] — всегда мягкие!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "щука", question: "Звук [Щ'] в слове «щука» — мягкий или твёрдый?", correct: "Всегда мягкий", options: ["Твёрдый", "Мягкий", "Всегда мягкий"], audio: "[Щ'] — всегда мягкий! Как [Ч'] и [Й']!", hint: "[Ч'], [Щ'], [Й'] — три звука, которые ВСЕГДА мягкие!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // Всегда твёрдые: Ж, Ш, Ц
  { type: "phonetics", word: "жук", question: "Звук [Ж] в слове «жук» — мягкий или твёрдый?", correct: "Всегда твёрдый", options: ["Мягкий", "Твёрдый", "Всегда твёрдый"], audio: "[Ж] — всегда твёрдый! Даже перед И и Е!", hint: "Запомни: [Ж], [Ш], [Ц] — всегда твёрдые!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "шить", question: "Звук [Ш] в слове «шить» — мягкий или твёрдый?", correct: "Всегда твёрдый", options: ["Мягкий", "Твёрдый", "Всегда твёрдый"], audio: "[Ш] — всегда твёрдый! Даже перед И!", hint: "[Ж], [Ш], [Ц] — три звука, которые ВСЕГДА твёрдые!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "цирк", question: "Звук [Ц] в слове «цирк» — мягкий или твёрдый?", correct: "Всегда твёрдый", options: ["Мягкий", "Твёрдый", "Всегда твёрдый"], audio: "[Ц] — всегда твёрдый! Даже перед И!", hint: "[Ж], [Ш], [Ц] — всегда твёрдые!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "жизнь", question: "В слове «жизнь» звук [Ж] — мягкий или твёрдый?", correct: "Всегда твёрдый", options: ["Мягкий (перед И)", "Всегда твёрдый"], audio: "[Ж] всегда твёрдый, даже перед И! Мы пишем ЖИ, но произносим [ЖЫ]!", hint: "[Ж] не бывает мягким! ЖИ-ШИ пиши с И, но звук [Ж] твёрдый!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "широкий", question: "В слове «широкий» звук [Ш] — мягкий или твёрдый?", correct: "Всегда твёрдый", options: ["Мягкий (перед И)", "Всегда твёрдый"], audio: "[Ш] всегда твёрдый! ШИ пиши с И, но звук [Ш] твёрдый!", hint: "[Ш] не бывает мягким!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 5: ЗВОНКИЕ И ГЛУХИЕ СОГЛАСНЫЕ
  // ============================================================

  { type: "phonetics", word: "б-п", question: "Какой звук звонкий: [Б] или [П]?", correct: "[Б] — звонкий", options: ["[Б] — звонкий", "[П] — звонкий", "Оба звонкие"], audio: "[Б] — звонкий, [П] — глухой! Они — парные!", hint: "Приложи руку к горлу: если дрожит — звонкий! Б-б-б — дрожит, П-п-п — не дрожит.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "д-т", question: "Какой звук глухой: [Д] или [Т]?", correct: "[Т] — глухой", options: ["[Д] — глухой", "[Т] — глухой", "Оба глухие"], audio: "[Т] — глухой! [Д] — его звонкая пара!", hint: "Парные: Б-П, В-Ф, Г-К, Д-Т, З-С, Ж-Ш. Первый — звонкий, второй — глухой.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "в-ф", question: "Какая пара: [В] — ?", correct: "[Ф]", options: ["[Ф]", "[Б]", "[С]"], audio: "[В] и [Ф] — звонко-глухая пара!", hint: "Парные: Б-П, В-Ф, Г-К, Д-Т, З-С, Ж-Ш.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "г-к", question: "Какая пара: [Г] — ?", correct: "[К]", options: ["[К]", "[Х]", "[Д]"], audio: "[Г] и [К] — звонко-глухая пара!", hint: "Парные: Б-П, В-Ф, Г-К, Д-Т, З-С, Ж-Ш.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "з-с", question: "Какая пара: [З] — ?", correct: "[С]", options: ["[С]", "[Ш]", "[Ц]"], audio: "[З] и [С] — звонко-глухая пара!", hint: "Парные: Б-П, В-Ф, Г-К, Д-Т, З-С, Ж-Ш.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // Всегда звонкие (сонорные)
  { type: "phonetics", word: "сонорные", question: "Какие согласные всегда звонкие (не имеют глухой пары)?", correct: "Л, М, Н, Р, Й", options: ["Л, М, Н, Р, Й", "Б, В, Г, Д, Ж", "Ж, Ш, Ц, Ч, Щ"], audio: "Л, М, Н, Р, Й — всегда звонкие! Их называют сонорные!", hint: "Запомни фразу: «Лимон — Рай!» — Л, М, Н, Р, Й.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  // Всегда глухие
  { type: "phonetics", word: "глухие непарные", question: "Какие согласные всегда глухие (не имеют звонкой пары)?", correct: "Х, Ц, Ч, Щ", options: ["Х, Ц, Ч, Щ", "Л, М, Н, Р", "П, Т, К, С"], audio: "Х, Ц, Ч, Щ — всегда глухие! У них нет звонкой пары!", hint: "Запомни: Х, Ц, Ч, Щ — глухие без пары!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // Оглушение на конце слова
  { type: "phonetics", word: "дуб", question: "Какой звук слышится на конце слова «дуб»?", correct: "[П]", options: ["[Б]", "[П]", "[В]"], audio: "Пишем Б, а слышим [П]! Звонкий [Б] оглушается на конце слова!", hint: "На конце слова звонкие согласные оглушаются: Б→П, Д→Т, Г→К.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "мороз", question: "Какой звук слышится на конце слова «мороз»?", correct: "[С]", options: ["[З]", "[С]", "[Ш]"], audio: "Пишем З, а слышим [С]! Проверяем: морозы — слышим [З]!", hint: "На конце слова звонкие оглушаются. Проверь: мороЗы!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "друг", question: "Какой звук слышится на конце слова «друг»?", correct: "[К]", options: ["[Г]", "[К]", "[Х]"], audio: "Пишем Г, а слышим [К]! Проверяем: друга — слышим [Г]!", hint: "Г оглушается в К на конце слова. Друг — друга.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "хлеб", question: "Какой звук слышится на конце слова «хлеб»?", correct: "[П]", options: ["[Б]", "[П]", "[Ф]"], audio: "Пишем Б, а слышим [П]! Хлеб — хлеба.", hint: "Б оглушается в П на конце. Проверяем: хлеба.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "город", question: "Какой звук слышится на конце слова «город»?", correct: "[Т]", options: ["[Д]", "[Т]", "[С]"], audio: "Пишем Д, а слышим [Т]! Город — города.", hint: "Д оглушается в Т на конце. Проверяем: города.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "нож", question: "Какой звук слышится на конце слова «нож»?", correct: "[Ш]", options: ["[Ж]", "[Ш]", "[С]"], audio: "Пишем Ж, а слышим [Ш]! Нож — ножи.", hint: "Ж оглушается в Ш на конце. Проверяем: ножи.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 6: НЕПРОИЗНОСИМЫЕ СОГЛАСНЫЕ
  // ============================================================

  { type: "phonetics", word: "солнце", question: "Какая буква не произносится в слове «солнце»?", correct: "Л", options: ["О", "Л", "Н"], audio: "Мы пишем Л, но не произносим: [сонцэ]! Проверяем: сОЛнышко!", hint: "Произнеси медленно: со-н-це. Буква Л молчит! Проверь: солнышко.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "сердце", question: "Какая буква не произносится в слове «сердце»?", correct: "Д", options: ["Р", "Д", "Е"], audio: "Мы пишем Д, но не произносим: [с'эрцэ]! Проверяем: серДечко!", hint: "Произнеси: сер-це. Д молчит! Проверь: сердечко — Д слышно!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "лестница", question: "Какая буква не произносится в слове «лестница»?", correct: "Т", options: ["С", "Т", "Н"], audio: "Мы пишем Т, но не произносим: [л'эсн'ица]! Это слово-словарное!", hint: "Произнеси: лес-ни-ца. Т молчит! Это нужно запомнить.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "праздник", question: "Какая буква не произносится в слове «праздник»?", correct: "Д", options: ["А", "Д", "Н"], audio: "Мы пишем Д, но не произносим: [праз'н'ик]!", hint: "Произнеси: праз-ник. Д молчит!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "честный", question: "Какая буква не произносится в слове «честный»?", correct: "Т", options: ["Ч", "Т", "Н"], audio: "Мы пишем Т, но не произносим: [ч'эсный]! Проверяем: чесТь!", hint: "Произнеси: чес-ный. Т молчит! Проверь: честь — Т слышно!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "местный", question: "Какая буква не произносится в слове «местный»?", correct: "Т", options: ["С", "Т", "Н"], audio: "Мы пишем Т, но не произносим: [м'эсный]! Проверяем: месТо!", hint: "Произнеси: мес-ный. Т молчит! Проверь: место — Т слышно!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "поздно", question: "Какая буква не произносится в слове «поздно»?", correct: "Д", options: ["О", "Д", "Н"], audio: "Мы пишем Д, но не произносим: [позна]! Проверяем: опозДать!", hint: "Произнеси: поз-но. Д молчит! Проверь: опоздать — Д слышно!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "звёздный", question: "Какая буква не произносится в слове «звёздный»?", correct: "Д", options: ["З", "Д", "Н"], audio: "Мы пишем Д, но не произносим: [зв'озный]! Проверяем: звезДа!", hint: "Произнеси: звёз-ный. Д молчит! Проверь: звезда — Д слышно!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "счастливый", question: "Какая буква не произносится в слове «счастливый»?", correct: "Т", options: ["С", "Т", "В"], audio: "Мы пишем Т, но не произносим: [щ'асл'ивый]! Проверяем: счасТье!", hint: "Произнеси: счас-ли-вый. Т молчит! Проверь: счастье.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 7: СРАВНЕНИЕ БУКВ И ЗВУКОВ
  // ============================================================

  { type: "phonetics", word: "тень", question: "В слове «тень» букв больше, чем звуков?", correct: "Да", options: ["Да", "Нет"], audio: "ТЕНЬ: 4 буквы (Т, Е, Н, Ь), но 3 звука [Т', Э, Н']. Ь не даёт звука!", hint: "Мягкий знак не даёт звука, поэтому букв больше!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "якорь", question: "В слове «якорь» букв и звуков поровну?", correct: "Да", options: ["Да", "Нет"], audio: "ЯКОРЬ: 5 букв. Я = 2 звука [Й'+А], но Ь забирает один. Итого 5 звуков!", hint: "Я в начале = 2 звука, Ь = 0 звуков. Считай!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "юбка", question: "В слове «юбка» звуков больше, чем букв?", correct: "Да", options: ["Да", "Нет"], audio: "ЮБКА: 4 буквы, но Ю в начале = 2 звука [Й'+У]. Итого 5 звуков!", hint: "Ю в начале слова = 2 звука. 4 буквы, 5 звуков!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "класс", question: "В слове «класс» букв больше, чем звуков?", correct: "Да", options: ["Да", "Нет"], audio: "КЛАСС: 5 букв, но две С произносятся как одна [С]. 4 звука!", hint: "Удвоенные согласные произносятся как один долгий звук!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "ёжик", question: "В слове «ёжик» звуков больше, чем букв?", correct: "Да", options: ["Да", "Нет"], audio: "ЁЖИК: 4 буквы. Ё в начале = 2 звука. Итого 5 звуков [Й'-О-Ж-Ы-К]!", hint: "Ё в начале = 2 звука. Букв 4, звуков 5!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 8: ОПРЕДЕЛЕНИЕ ХАРАКТЕРИСТИКИ ЗВУКА
  // ============================================================

  { type: "phonetics", word: "река", question: "Охарактеризуй первый звук в слове «река»", correct: "Согласный, звонкий, мягкий", options: ["Согласный, звонкий, мягкий", "Согласный, глухой, твёрдый", "Гласный, ударный"], audio: "[Р'] — согласный (нельзя пропеть), звонкий (горло дрожит), мягкий (перед Е)!", hint: "Р — согласный. Он звонкий (сонорный). Перед Е — мягкий.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "кот", question: "Охарактеризуй первый звук в слове «кот»", correct: "Согласный, глухой, твёрдый", options: ["Согласный, звонкий, мягкий", "Согласный, глухой, твёрдый", "Гласный, безударный"], audio: "[К] — согласный, глухой (горло не дрожит), твёрдый (перед О)!", hint: "К — глухой согласный (пара Г-К). Перед О — твёрдый.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "зима", question: "Охарактеризуй первый звук в слове «зима»", correct: "Согласный, звонкий, мягкий", options: ["Согласный, звонкий, мягкий", "Согласный, глухой, твёрдый", "Согласный, звонкий, твёрдый"], audio: "[З'] — согласный, звонкий (пара З-С), мягкий (перед И)!", hint: "З — звонкий (пара З-С). Перед И — мягкий.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "шар", question: "Охарактеризуй первый звук в слове «шар»", correct: "Согласный, глухой, всегда твёрдый", options: ["Согласный, глухой, всегда твёрдый", "Согласный, звонкий, твёрдый", "Согласный, глухой, мягкий"], audio: "[Ш] — согласный, глухой (пара Ж-Ш), всегда твёрдый!", hint: "Ш — глухой (пара Ж-Ш). Всегда твёрдый, даже перед И!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 9: УДАРНЫЕ И БЕЗУДАРНЫЕ ГЛАСНЫЕ (звуковой анализ)
  // ============================================================

  { type: "phonetics", word: "вода", question: "Какой гласный звук ударный в слове «вода»?", correct: "[А]", options: ["[О]", "[А]"], audio: "ВодА — ударение на А! Безударная О звучит как [А].", hint: "Поставь ударение: водА. Ударный звук — последний!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "леса", question: "Какой гласный звук ударный в слове «леса»?", correct: "[А]", options: ["[Э]", "[А]", "[И]"], audio: "ЛесА — ударение на А! Безударная Е звучит ближе к [И].", hint: "Поставь ударение: лесА. Ударный — последний гласный.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "город", question: "Сколько ударных гласных может быть в слове?", correct: "Только 1", options: ["Только 1", "2", "Сколько угодно"], audio: "В каждом слове только ОДНО ударение! Один ударный гласный!", hint: "Запомни: в каждом слове только один ударный гласный звук!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // ============================================================
  // БЛОК 10: ПЕРЕНОС СЛОВ
  // ============================================================

  { type: "phonetics", word: "мо-ло-ко", question: "Как правильно перенести слово «молоко»?", correct: "мо-ло-ко", options: ["мо-ло-ко", "мол-ок-о", "м-оло-ко"], audio: "Мо-ло-ко — переносим по слогам!", hint: "Слово переносится по слогам. Нельзя оставлять одну букву!", rule: RULE_TRANSFER, ruleId: RULE_ID_TRANSFER, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "учи-тель", question: "Как правильно перенести слово «учитель»?", correct: "учи-тель", options: ["учи-тель", "у-читель", "учит-ель"], audio: "Учи-тель! Нельзя оставлять одну букву на строке!", hint: "Нельзя оставлять одну букву! У-читель — неправильно!", rule: RULE_TRANSFER, ruleId: RULE_ID_TRANSFER, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "объ-яв-ле-ние", question: "Как правильно перенести слово «объявление»?", correct: "объ-яв-ле-ние", options: ["объ-яв-ле-ние", "об-ъяв-ле-ние", "объя-вле-ние"], audio: "Объ-яв-ле-ние! Ъ остаётся с предыдущей согласной!", hint: "Ъ и Ь нельзя отрывать от предыдущей буквы!", rule: RULE_TRANSFER, ruleId: RULE_ID_TRANSFER, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "клас-сный", question: "Как правильно перенести слово «классный»?", correct: "клас-сный", options: ["клас-сный", "кла-ссный", "класс-ный"], audio: "Клас-сный! Удвоенные согласные разделяются при переносе!", hint: "Удвоенные согласные при переносе разделяются: одна остаётся, другая переносится.", rule: RULE_TRANSFER, ruleId: RULE_ID_TRANSFER, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "подъ-езд", question: "Как правильно перенести слово «подъезд»?", correct: "подъ-езд", options: ["подъ-езд", "под-ъезд", "по-дъезд"], audio: "Подъ-езд! Ъ остаётся с буквой перед ним!", hint: "Ъ нельзя отрывать от предыдущей буквы!", rule: RULE_TRANSFER, ruleId: RULE_ID_TRANSFER, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "аист", question: "Можно ли перенести слово «аист»?", correct: "Нельзя перенести", options: ["А-ист", "Аи-ст", "Нельзя перенести"], audio: "Нельзя оставлять одну букву! А-ист — неправильно. Аи-ст — ст не слог. Нельзя перенести!", hint: "Одну букву нельзя оставлять на строке или переносить!", rule: RULE_TRANSFER, ruleId: RULE_ID_TRANSFER, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "паль-то", question: "Как правильно перенести слово «пальто»?", correct: "паль-то", options: ["паль-то", "пал-ьто", "па-льто"], audio: "Паль-то! Ь остаётся с предыдущей буквой!", hint: "Ь нельзя отрывать от предыдущей буквы!", rule: RULE_TRANSFER, ruleId: RULE_ID_TRANSFER, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "строй-ка", question: "Как правильно перенести слово «стройка»?", correct: "строй-ка", options: ["строй-ка", "стро-йка", "стр-ойка"], audio: "Строй-ка! Й остаётся с предыдущей буквой!", hint: "Й нельзя отрывать от предыдущей гласной!", rule: RULE_TRANSFER, ruleId: RULE_ID_TRANSFER, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "чай-ник", question: "Как правильно перенести слово «чайник»?", correct: "чай-ник", options: ["чай-ник", "ча-йник", "чайн-ик"], audio: "Чай-ник! Й остаётся с гласной перед ней!", hint: "Й нельзя отрывать от предыдущей гласной!", rule: RULE_TRANSFER, ruleId: RULE_ID_TRANSFER, difficulty: 1, category: "phonetics" },

  // ============================================================
  // БЛОК 11: ДОПОЛНИТЕЛЬНЫЕ ЗАДАНИЯ НА БУКВЫ И ЗВУКИ
  // ============================================================

  { type: "phonetics", word: "лук — люк", question: "Чем отличаются слова «лук» и «люк» по звукам?", correct: "Первый звук: [Л] твёрдый и [Л'] мягкий", options: ["Первый звук: [Л] твёрдый и [Л'] мягкий", "Последний звук разный", "Ничем не отличаются"], audio: "ЛУК — [Л] твёрдый (перед У). ЛЮК — [Л'] мягкий (перед Ю). Вот и разница!", hint: "У не смягчает согласный, а Ю — смягчает!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "мал — мял", question: "Чем отличаются слова «мал» и «мял» по звукам?", correct: "Первый звук: [М] твёрдый и [М'] мягкий", options: ["Первый звук: [М] твёрдый и [М'] мягкий", "Гласный звук разный", "Ничем не отличаются"], audio: "МАЛ — [М] твёрдый. МЯЛ — [М'] мягкий. Гласный один и тот же — [А]!", hint: "А не смягчает, Я — смягчает. Но оба дают звук [А]!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "нос — нёс", question: "Чем отличаются слова «нос» и «нёс» по звукам?", correct: "Первый звук: [Н] твёрдый и [Н'] мягкий", options: ["Первый звук: [Н] твёрдый и [Н'] мягкий", "Последний звук разный", "Гласный разный: [О] и [Ё]"], audio: "НОС — [Н] твёрдый. НЁС — [Н'] мягкий. Гласный звук одинаковый — [О]!", hint: "Ё смягчает Н, но гласный звук тот же — [О]!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // Подсчёт звуков в сложных словах
  { type: "phonetics", word: "деревья", question: "Сколько звуков в слове «деревья»?", correct: "7", options: ["6", "7", "8"], audio: "Д'-Э-Р'-Э-В'-Й-А = 7! Ь не звук, Я после Ь = два звука.", hint: "Ь звука не даёт, но Я после Ь = [Й'] + [А].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "муравьи", question: "Сколько звуков в слове «муравьи»?", correct: "7", options: ["6", "7", "8"], audio: "М-У-Р-А-В'-Й-И = 7! Ь не звук, И после Ь = два звука.", hint: "Ь звука не даёт, но И после Ь = [Й'] + [И].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "объезд", question: "Сколько звуков в слове «объезд»?", correct: "6", options: ["5", "6", "7"], audio: "О-Б-Й-Э-З-Д = 6! Ъ не звук, Е после Ъ = два звука.", hint: "Ъ не даёт звука, Е после Ъ = [Й'] + [Э].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "ягода", question: "Сколько звуков в слове «ягода»?", correct: "6", options: ["5", "6", "7"], audio: "Й-А-Г-О-Д-А = 6! Я в начале = два звука.", hint: "Я в начале слова = [Й'] + [А].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "ёлочка", question: "Сколько звуков в слове «ёлочка»?", correct: "7", options: ["6", "7", "8"], audio: "Й-О-Л-О-Ч'-К-А = 7! Ё в начале = два звука.", hint: "Ё в начале слова = [Й'] + [О].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // ============================================================
  // БЛОК 12: ЖИ-ШИ, ЧА-ЩА, ЧУ-ЩУ (орфограммы с фонетикой)
  // ============================================================

  { type: "phonetics", word: "машина", question: "Какой гласный звук слышится после Ш в слове «машина»?", correct: "[Ы]", options: ["[И]", "[Ы]", "[А]"], audio: "Мы пишем ШИ, но произносим [ШЫ]! Потому что [Ш] всегда твёрдый!", hint: "Ш всегда твёрдый, поэтому после него слышится [Ы], а пишем И!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "живот", question: "Какой гласный звук слышится после Ж в слове «живот»?", correct: "[Ы]", options: ["[И]", "[Ы]", "[О]"], audio: "Мы пишем ЖИ, но произносим [ЖЫ]! Потому что [Ж] всегда твёрдый!", hint: "Ж всегда твёрдый, после него слышится [Ы], а пишем И!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "чаща", question: "Почему в слове «чаща» после Ч и Щ пишем А?", correct: "ЧА-ЩА пишется с А, хотя Ч и Щ мягкие", options: ["ЧА-ЩА пишется с А, хотя Ч и Щ мягкие", "Потому что слышится А", "Потому что Ч и Щ твёрдые"], audio: "ЧА-ЩА пиши с буквой А! Хотя [Ч'] и [Щ'] всегда мягкие — это правило!", hint: "Запомни: ЧА-ЩА с А, ЧУ-ЩУ с У — это орфограмма!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // ============================================================
  // БЛОК 13: ДОПОЛНИТЕЛЬНЫЕ ЗАДАНИЯ — ХАРАКТЕРИСТИКА ЗВУКОВ
  // ============================================================

  { type: "phonetics", word: "небо", question: "Сколько мягких согласных в слове «небо»?", correct: "1", options: ["0", "1", "2"], audio: "[Н'] мягкий (перед Е), [Б] твёрдый (перед О). Один мягкий!", hint: "Проверь каждый согласный: Н перед Е — мягкий, Б перед О — твёрдый.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "песня", question: "Сколько мягких согласных в слове «песня»?", correct: "3", options: ["1", "2", "3"], audio: "[П'] мягкий (перед Е), [С'] мягкий (перед Н'), [Н'] мягкий (перед Я). Три!", hint: "Е смягчает П, а Я смягчает Н. С перед мягким Н тоже смягчается!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "лиса", question: "Сколько мягких согласных в слове «лиса»?", correct: "1", options: ["0", "1", "2"], audio: "[Л'] мягкий (перед И), [С] твёрдый (перед А). Один мягкий!", hint: "И смягчает Л. А не смягчает С.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "берёза", question: "Сколько мягких согласных в слове «берёза»?", correct: "2", options: ["1", "2", "3"], audio: "[Б'] мягкий (перед Е), [Р'] мягкий (перед Ё), [З] твёрдый (перед А). Два!", hint: "Е смягчает Б, Ё смягчает Р. А не смягчает З.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // Звонкие согласные в слове
  { type: "phonetics", word: "загадка", question: "Сколько звонких согласных звуков в слове «загадка»?", correct: "2", options: ["2", "3", "4"], audio: "[З] звонкий, [Г] звонкий, [Д] оглушается перед К в [Т], [К] глухой. Два звонких!", hint: "Д перед глухой К оглушается в [Т]. Звонкие: З, Г.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "сказка", question: "Сколько глухих согласных звуков в слове «сказка»?", correct: "4", options: ["2", "3", "4"], audio: "[С] глухой, [К] глухой, [С] (З оглушается!), [К] глухой. Четыре!", hint: "З перед глухой К оглушается в [С]!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 14: ТРАНСКРИПЦИЯ
  // ============================================================

  { type: "phonetics", word: "яблоня", question: "Какая транскрипция у слова «яблоня»?", correct: "[й'аблан'а]", options: ["[й'аблан'а]", "[яблоня]", "[й'аблон'а]"], audio: "Я в начале = [Й'+А], безударная О = [А], Я на конце после Н = [А] и смягчает Н.", hint: "Я в начале = [Й'А]. Безударная О звучит как [А].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "ёжик", question: "Какая транскрипция у слова «ёжик»?", correct: "[й'ожык]", options: ["[й'ожык]", "[ёжик]", "[й'ожик]"], audio: "Ё в начале = [Й'+О], ЖИ = [ЖЫ] потому что Ж всегда твёрдый!", hint: "Ё в начале = [Й'О]. Ж всегда твёрдый: ЖИ = [ЖЫ].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "лёгкий", question: "Как произносится буква Г в слове «лёгкий»?", correct: "[Х]", options: ["[Г]", "[К]", "[Х]"], audio: "В сочетании ГК буква Г произносится как [Х]: лё[хк']ий!", hint: "В сочетаниях ГК и ГЧ буква Г читается как [Х].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "что", question: "Как произносится сочетание ЧТ в слове «что»?", correct: "[ШТ]", options: ["[ЧТ]", "[ШТ]", "[Щ]"], audio: "Что = [ШТО]! Буква Ч произносится как [Ш]!", hint: "В словах «что», «чтобы», «ничто» ЧТ читается как [ШТ].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "конечно", question: "Как произносится сочетание ЧН в слове «конечно»?", correct: "[ШН]", options: ["[ЧН]", "[ШН]", "[Щ'Н]"], audio: "Конечно = коне[ШН]о! Так же: скучно, нарочно.", hint: "В некоторых словах ЧН читается как [ШН]: конечно, скучно, нарочно.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 15: СЛОГИ — ДОПОЛНИТЕЛЬНЫЕ ЗАДАНИЯ
  // ============================================================

  { type: "phonetics", word: "страна", question: "Сколько слогов в слове «страна»?", correct: "2", options: ["1", "2", "3"], audio: "Стра-на. Два гласных — два слога!", hint: "Сколько гласных, столько и слогов!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "электричество", question: "Сколько слогов в слове «электричество»?", correct: "5", options: ["4", "5", "6"], audio: "Э-лек-три-чес-тво. Пять гласных — пять слогов!", hint: "Посчитай гласные: Э, Е, И, Е, О = 5.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "крот", question: "Сколько слогов в слове «крот»?", correct: "1", options: ["1", "2", "3"], audio: "Крот — один гласный О, один слог!", hint: "Один гласный = один слог!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "земляника", question: "Сколько слогов в слове «земляника»?", correct: "4", options: ["3", "4", "5"], audio: "Зем-ля-ни-ка. Четыре гласных — четыре слога!", hint: "Гласные: Е, Я, И, А = 4 слога.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // ============================================================
  // БЛОК 16: ДОПОЛНИТЕЛЬНЫЕ — БУКВЫ И ЗВУКИ В СЛОВАХ
  // ============================================================

  { type: "phonetics", word: "Россия", question: "Сколько звуков в слове «Россия»?", correct: "6", options: ["5", "6", "7"], audio: "Р-А-С'-И-Й-А = 6! Удвоенная С = один долгий звук, И после И = Й+А? Нет: Россия: Р-О-С'-И-Й-А.", hint: "Удвоенная СС = один звук [С']. Я после И = [Й'] + [А].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "солнышко", question: "В слове «солнышко» все буквы произносятся?", correct: "Да", options: ["Да", "Нет"], audio: "Сол-ныш-ко. В отличие от «солнце», здесь Л произносится!", hint: "В «солнце» Л не произносится, а в «солнышко» — слышна!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "грустный", question: "Какая буква не произносится в слове «грустный»?", correct: "Т", options: ["Р", "Т", "Н"], audio: "Грус-ный — Т молчит! Проверяем: грусТить — Т слышно!", hint: "Произнеси: грус-ный. Т не произносится! Проверка: грустить.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "чувство", question: "Какая буква не произносится в слове «чувство»?", correct: "Первая В", options: ["Ч", "Первая В", "Т"], audio: "Чу-ство — первая В молчит! Это словарное слово!", hint: "Произнеси: чу-ство. Первая В не произносится!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "здравствуй", question: "Какая буква не произносится в слове «здравствуй»?", correct: "В (первая)", options: ["Д", "В (первая)", "Й"], audio: "Здра-ствуй — первая В молчит! Проверяем: здраВие!", hint: "Произнеси: здра-ствуй. Первая В не произносится!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 17: ИТОГОВЫЕ — КОМПЛЕКСНЫЙ АНАЛИЗ
  // ============================================================

  { type: "phonetics", word: "юность", question: "В слове «юность»: букв больше, меньше или столько же, сколько звуков?", correct: "Букв больше", options: ["Букв больше", "Звуков больше", "Поровну"], audio: "ЮНОСТЬ: 6 букв. Ю = 2 звука [Й'+У], но Ь = 0 звуков. Итого 6 букв, 5 звуков!", hint: "Ю в начале = 2 звука, Ь = 0 звуков. 6 букв, 5 звуков.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "пою", question: "В слове «пою»: букв больше, меньше или столько же, сколько звуков?", correct: "Звуков больше", options: ["Букв больше", "Звуков больше", "Поровну"], audio: "ПОЮ: 3 буквы. Ю после гласной = 2 звука. Итого 4 звука, 3 буквы!", hint: "Ю после гласной О = [Й'] + [У]. 3 буквы, 4 звука.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "коньки", question: "В слове «коньки»: букв больше, меньше или столько же, сколько звуков?", correct: "Букв больше", options: ["Букв больше", "Звуков больше", "Поровну"], audio: "КОНЬКИ: 6 букв, 5 звуков. Ь не даёт звука!", hint: "Ь не даёт звука. 6 букв, 5 звуков.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "ёлки", question: "В слове «ёлки»: букв больше, меньше или столько же, сколько звуков?", correct: "Звуков больше", options: ["Букв больше", "Звуков больше", "Поровну"], audio: "ЁЛКИ: 4 буквы. Ё в начале = 2 звука. Итого 5 звуков, 4 буквы!", hint: "Ё в начале = [Й'] + [О]. 4 буквы, 5 звуков!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // Дополнительные задания
  { type: "phonetics", word: "подружка", question: "В слове «подружка» звук [Ж] оглушается?", correct: "Да, перед К", options: ["Да, перед К", "Нет"], audio: "Подру[Ш]ка — [Ж] перед глухой [К] оглушается в [Ш]!", hint: "Звонкий согласный перед глухим оглушается: Ж → Ш.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "просьба", question: "В слове «просьба» звук [С] озвончается?", correct: "Да, перед Б", options: ["Да, перед Б", "Нет"], audio: "Про[З']ба — [С'] перед звонкой [Б] озвончается в [З']!", hint: "Глухой согласный перед звонким озвончается: С → З.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "сделать", question: "Какой первый звук в слове «сделать»?", correct: "[З]", options: ["[С]", "[З]", "[Д]"], audio: "С перед звонкой Д озвончается! [З]делать!", hint: "Глухой С перед звонким Д → озвончается в [З]!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "лодка", question: "Какой звук на месте буквы Д в слове «лодка»?", correct: "[Т]", options: ["[Д]", "[Т]", "[К]"], audio: "Ло[Т]ка — [Д] перед глухой [К] оглушается в [Т]!", hint: "Звонкий Д перед глухим К оглушается в [Т].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "варежка", question: "Какой звук на месте буквы Ж в слове «варежка»?", correct: "[Ш]", options: ["[Ж]", "[Ш]", "[Щ']"], audio: "Варе[Ш]ка — [Ж] перед глухой [К] оглушается в [Ш]!", hint: "Ж перед глухим К → [Ш].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 18: ГЛАСНЫЕ ЗВУКИ — ДОПОЛНИТЕЛЬНЫЕ
  // ============================================================

  { type: "phonetics", word: "гласные", question: "Сколько гласных звуков в русском языке?", correct: "6", options: ["6", "10", "5"], audio: "Гласных звуков всего 6: [А], [О], [У], [Э], [И], [Ы]. А букв — 10!", hint: "Звуков 6: А, О, У, Э, И, Ы. Букв 10: + Е, Ё, Ю, Я.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "согласные", question: "В русском языке гласных звуков больше или согласных?", correct: "Согласных больше", options: ["Гласных больше", "Согласных больше", "Поровну"], audio: "Согласных звуков гораздо больше! 6 гласных и 36 согласных!", hint: "Гласных звуков 6, а согласных — 36!", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },

  // ============================================================
  // БЛОК 19: ЕЩЁ ЗАДАНИЯ НА ПОДСЧЁТ
  // ============================================================

  { type: "phonetics", word: "южный", question: "Сколько звуков в слове «южный»?", correct: "6", options: ["5", "6", "7"], audio: "Й-У-Ж-Н-Ы-Й = 6! Ю в начале = 2 звука, Й на конце.", hint: "Ю в начале = [Й'] + [У].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "поют", question: "Сколько звуков в слове «поют»?", correct: "5", options: ["4", "5", "6"], audio: "П-О-Й-У-Т = 5! Ю после гласной = 2 звука.", hint: "Ю после гласной О = [Й'] + [У].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "ручьи", question: "Сколько звуков в слове «ручьи»?", correct: "5", options: ["4", "5", "6"], audio: "Р-У-Ч'-Й-И = 5! Ь не даёт звука, И после Ь = 2 звука.", hint: "Ь не звук. И после Ь = [Й'] + [И].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "вьётся", question: "Сколько звуков в слове «вьётся»?", correct: "5", options: ["4", "5", "6"], audio: "В'-Й-О-Ц-А = 5! Ь не звук, Ё после Ь = 2 звука, ТСЯ = [ЦА].", hint: "Ь не звук. Ё после Ь = [Й'О]. -ТСЯ произносится как [ЦА].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "съёмка", question: "Сколько звуков в слове «съёмка»?", correct: "6", options: ["5", "6", "7"], audio: "С-Й-О-М-К-А = 6! Ъ не звук, Ё после Ъ = 2 звука.", hint: "Ъ не даёт звука. Ё после Ъ = [Й'] + [О].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // ============================================================
  // БЛОК 20: СЛОВА ИЗ СПИСКА ВПР (дополнение)
  // ============================================================

  // --- Звуков больше, чем букв ---
  { type: "phonetics", word: "поезд", question: "Сколько звуков в слове «поезд»?", correct: "6", options: ["5", "6", "7"], audio: "П-О-Й-Э-С-Т = 6 звуков! Е после гласной О = два звука [Й'Э]. ЗД на конце оглушаются в [СТ]. 5 букв, 6 звуков!", hint: "Е после гласной = [Й'] + [Э]. ЗД на конце оглушаются в [СТ].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "ястреб", question: "Сколько звуков в слове «ястреб»?", correct: "7", options: ["6", "7", "8"], audio: "Й-А-С-Т-Р'-Э-П = 7 звуков! Я в начале = два звука [Й'А]. 6 букв, 7 звуков!", hint: "Я в начале слова = [Й'] + [А]. Б на конце оглушается в [П].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // --- Звуков меньше, чем букв (непроизносимые согласные) ---
  { type: "phonetics", word: "дождь", question: "Сколько звуков в слове «дождь»?", correct: "4", options: ["3", "4", "5"], audio: "Д-О-Ш-Т' = 4 звука! Ь не даёт звука, ЖД на конце звучит как [ШТ']. 5 букв, 4 звука!", hint: "Ь не даёт звука. На конце ЖД произносится как [ШТ'].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "радостный", question: "Какая буква не произносится в слове «радостный»?", correct: "Т", options: ["Д", "Т", "Н"], audio: "Радос-ный — Т между С и Н не произносится! Проверяем: радосТи — Т слышно! 9 букв, 8 звуков.", hint: "Т между СТН не произносится. Проверка: радости.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "местность", question: "Сколько звуков в слове «местность»?", correct: "7", options: ["7", "8", "9"], audio: "М'-Э-С-Н-А-С'-Т' = 7 звуков! Т не произносится (стн), Ь не даёт звука. 9 букв, 7 звуков!", hint: "Т в сочетании СТН не произносится. Ь не звук. 9 букв → 7 звуков.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // --- Букв и звуков одинаково ---
  { type: "phonetics", word: "платье", question: "Сколько звуков в слове «платье»?", correct: "6", options: ["5", "6", "7"], audio: "П-Л-А-Т'-Й-Э = 6 звуков! Ь не даёт звука, но Е после Ь = два звука [Й'Э]. 6 букв = 6 звуков!", hint: "Ь не звук (-1), но Е после Ь = 2 звука (+1). Итого поровну: 6 = 6.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "друзья", question: "Сколько звуков в слове «друзья»?", correct: "6", options: ["5", "6", "7"], audio: "Д-Р-У-З'-Й-А = 6 звуков! Ь не звук, но Я после Ь = два звука [Й'А]. 6 букв = 6 звуков!", hint: "Ь не звук (-1), Я после Ь = 2 звука (+1). 6 букв = 6 звуков.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "вьюн", question: "Сколько звуков в слове «вьюн»?", correct: "4", options: ["3", "4", "5"], audio: "В'-Й-У-Н = 4 звука! Ь не звук, Ю после Ь = два звука [Й'У]. 4 буквы = 4 звука!", hint: "Ь не звук (-1), Ю после Ь = 2 звука (+1). 4 буквы = 4 звука.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "сыновья", question: "Сколько звуков в слове «сыновья»?", correct: "7", options: ["6", "7", "8"], audio: "С-Ы-Н-А-В'-Й-А = 7 звуков! Ь не звук, Я после Ь = два звука [Й'А]. 7 букв = 7 звуков!", hint: "Ь не звук (-1), Я после Ь = 2 звука (+1). 7 букв = 7 звуков.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // --- Удвоенные согласные (один долгий звук) ---
  { type: "phonetics", word: "суббота", question: "Сколько звуков в слове «суббота»?", correct: "6", options: ["5", "6", "7"], audio: "С-У-Б-О-Т-А = 6 звуков! Удвоенная ББ = один долгий звук [Б]. 7 букв, 6 звуков!", hint: "Удвоенные согласные (ББ) произносятся как один долгий звук.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "хоккей", question: "Сколько звуков в слове «хоккей»?", correct: "5", options: ["4", "5", "6"], audio: "Х-О-К'-Э-Й = 5 звуков! Удвоенная КК = один долгий звук. 6 букв, 5 звуков!", hint: "Удвоенные согласные (КК) = один звук. Е после К = [Э] и смягчает.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "группа", question: "Сколько звуков в слове «группа»?", correct: "5", options: ["4", "5", "6"], audio: "Г-Р-У-П-А = 5 звуков! Удвоенная ПП = один долгий звук. 6 букв, 5 звуков!", hint: "Удвоенные согласные (ПП) произносятся как один звук.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },

  // --- Дополнительные слова ---
  { type: "phonetics", word: "речь", question: "Сколько звуков в слове «речь»?", correct: "3", options: ["2", "3", "4"], audio: "Р'-Э-Ч' = 3 звука! Ь не даёт звука. 4 буквы, 3 звука!", hint: "Ь не даёт звука. Е после Р = [Э] и смягчает.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "снег", question: "Сколько звуков в слове «снег»?", correct: "4", options: ["3", "4", "5"], audio: "С-Н'-Э-К = 4 звука! Г на конце оглушается в [К]. 4 буквы = 4 звука!", hint: "Г на конце слова оглушается: [Г] → [К].", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "птичка", question: "Сколько звуков в слове «птичка»?", correct: "6", options: ["5", "6", "7"], audio: "П-Т'-И-Ч'-К-А = 6 звуков! Все буквы произносятся. 6 букв = 6 звуков!", hint: "Каждая буква даёт звук. 6 букв = 6 звуков.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "тростник", question: "Сколько звуков в слове «тростник»?", correct: "7", options: ["6", "7", "8"], audio: "Т-Р-А-С-Н'-И-К = 7 звуков! Т между С и Н не произносится. 8 букв, 7 звуков!", hint: "Т в сочетании СТН не произносится. Проверяем: тросТиночка.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "осенью", question: "Сколько звуков в слове «осенью»?", correct: "6", options: ["5", "6", "7"], audio: "О-С'-Э-Н'-Й-У = 6 звуков! Ь не звук, Ю после Ь = два звука [Й'У]. 6 букв = 6 звуков!", hint: "Ь не звук (-1), Ю после Ь = 2 звука (+1). 6 букв = 6 звуков.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
  { type: "phonetics", word: "мать", question: "Сколько звуков в слове «мать»?", correct: "3", options: ["2", "3", "4"], audio: "М-А-Т' = 3 звука! Ь не даёт звука, только смягчает Т. 4 буквы, 3 звука!", hint: "Ь не даёт звука, он только смягчает согласную.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 1, category: "phonetics" },
  { type: "phonetics", word: "подъём", question: "Сколько звуков в слове «подъём»?", correct: "6", options: ["5", "6", "7"], audio: "П-А-Д-Й-О-М = 6 звуков! Ъ не звук, Ё после Ъ = два звука [Й'О]. 6 букв = 6 звуков!", hint: "Ъ не звук (-1), Ё после Ъ = 2 звука (+1). 6 букв = 6 звуков.", rule: RULE_SOUNDS, ruleId: RULE_ID_PHONETICS, difficulty: 2, category: "phonetics" },
];
